package com.API_SupportCustommer.API.enuns;

public enum TypeProblemEnum {
    TECHNICAL_ISSUES,
    ACCOUNT_AND_ACCESS_PROBLEMS,
    PRODUCT_AND_SERVICE_ISSUES,
    BILLING_AND_PAYMENT_PROBLEMS,
    CUSTOMER_SERVICE_ISSUES,
    USABILITY_PROBLEMS,
    SECURITY_ISSUES,
    FUNCTIONALITY_PROBLEMS
}
